### ISSUE TITLE
pip install error in python3

### ISSUE THREAD

**Issue by eyaler** [iansf/qj#2]
Collecting qj
  Using cached https://files.pythonhosted.org/packages/dc/cf/27b29569f09255f0b52c75dd4650677eb818cf1318890fa40a877edcc545/qj-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\e\AppData\Local\Temp\pip-install-wq1ej890\qj\setup.py", line 31, in <module>
        long_description=readme(),
      File "C:\Users\e\AppData\Local\Temp\pip-install-wq1ej890\qj\setup.py", line 21, in readme
        return f.read()
      File "C:\anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 74: character maps to <undefined>

**Comment by iansf** [comment]
Thanks for the bug report! I wasn't specifying that the readme should be opened as a unicode file, so that's probably why you hit this (although I'm not able to reproduce it -- I'm guessing the anaconda environment you're using has an earlier version of python3 than I'm using). If you're able to try it again, I've pushed 0.1.5 that should fix the issue. Please reopen if you're still unable to install.

**Comment by eyaler** [comment]
i am using python 3.6.7. anyway 0.1.5 installs fine.
